### PR TITLE
Add `expire_seconds:` TTL option to RedisAdapter

### PR DESCRIPTION
**Pull request by karmakaze**
Issue #403 Support TTL for participants in RedisAdapter

### CODE REVIEW

**Comment by andrew** [comment]
Great, thanks @karmakaze!

**Comment by karmakaze** [comment]
@andrew Thanks for accepting and the quick merge. I'm hoping to address one more issue and then ask for a gem dot-version release.

**Comment by andrew** [comment]
👌

**Comment by andrew** [comment]
@karmakaze just released this as part of v1.5.0: https://github.com/splitrb/split/releases/tag/v1.5.0

**Pull request merged**
