### PR TITLE
Return an empty hash as metadata when Split is disabled

### PR DESCRIPTION
**Pull request by tomasdundacek**

### CODE REVIEW

**Comment by tomasdundacek** [comment]
This PR is actually dependent on #312 , will need to be rebased after it is merged.

**Comment by andrew** [comment]
Rebase away!

**Comment by tomasdundacek** [comment]
@andrew done

**Comment by andrew** [comment]
Nice, I'll look at getting a release out later today

**Comment by andrew** [comment]
:ship: https://github.com/splitrb/split/releases/tag/v1.2.1

**Comment by tomasdundacek** [comment]
:clap:

**Pull request merged**
