### PR TITLE
CI: Change and test earliest supported Ruby version (1.9.2 -> 2.2.0)

### PR DESCRIPTION
**Pull request by patbl**
See #494.

https://github.com/splitrb/split/blob/07b71cec9f220a16795811dcf9feca5d795bd15f/split.gemspec#L24

### CODE REVIEW

**Comment by andrew** [comment]
Thanks for tackling this @patbl, as I mentioned in #494, it's probably not worth the effort to continue to support 1.9.3, can you update this pr to test against 2.2 instead?

**Comment by patbl** [comment]
The specs are passing. I changed the minimum Ruby version to 2.2.2 instead of 2.2.0 because 2.2.2 is compatible with Rails 5.0. The other option is to make the minimum version 2.2.0 and test it only against Rails 4.2 (and maybe separately test 2.2.2 against both Rails 4.2 and 5.0).

**Comment by patbl** [comment]
Actually, it's not much trouble to get it working with 2.2.0 so I went ahead and did that.

Unfortunately, there's now a failing spec. I think it's unrelated to my changes.

```
 1) Split::Experiment beta probability calculation should calculate the probability of being the winning alternative separately for each goal
     Failure/Error: expect(p_goal1).not_to be_within(0.04).of(p_goal2)
       expected 0.3394 not to be within 0.04 of 0.3525
     # ./spec/experiment_spec.rb:474:in `block (3 levels) in <top (required)>'
```

**Comment by patbl** [comment]
I re-ran the build and it passed, so I think that failure was transient and unrelated to my changes.

**Comment by andrew** [comment]
Yeah that test does fail every so often 😬

**Comment by iwz** [comment]
👏  thanks!!

**Pull request merged**
