### PR TITLE
144867444998371 dual cookie redis split persistence adapter

### PR DESCRIPTION
**Pull request by karmakaze**
Issue #404 Use different persistence adapter for logged-in vs. logged-out users

Note: this branch first merges v1.5.0 into master branch which had diverged.

### CODE REVIEW

**Comment by andrew** [comment]
oh that's weird you have commits from me in your branch, might be worth rebasing against master to only leave your commit as different.

**Comment by karmakaze** [comment]
The problem is that I'm adding to v1.5.0 and master does not include it.

**Comment by andrew** [comment]
Oh right my fault!

**Comment by andrew** [comment]
Thanks! Will do a release shortly

**Comment by karmakaze** [comment]
Thanks, no problemo

**Pull request merged**
